environment:
  matrix:
    - nodejs_version: "8"

version: "{build}"

init: 
  - "git config --global core.autocrlf input"

shallow_clone: true

services:
  - mssql2014

install:
  - node --version
  - npm --version
  - ps: Install-Product node $env:nodejs_version x64
  - npm i -g npm@5.3
  - node --version
  - npm --version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install


build: off

test_script:
  - cmd: npm run lint
  - cmd: npm test

cache:
  - node_modules -> package.json

notifications:
  - provider: GitHubPullRequest
    template: |
      {{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
      {{#jobs}}
      {{#messages}}
      - :warning: [{{message}}]({{details}})
      {{/messages}}
      {{/jobs}}
