branches: 
  only: 
    - master 
 
environment:
  npm_auth_token:
    secure: eSBcha8PsT3+GQ3n8jFRhNX5bCR/zN0RQZHIbiFsFTj70zkRtyhkolOvY8ENRVKc

version: "{build}"

init: 
  - "git config --global core.autocrlf input"

shallow_clone: true

services:
  - mssql2014

install:
  - node --version
  - npm --version
  - ps: Install-Product node 8.16.0
  - npm i -g npm@6.4.1
  - node --version
  - npm --version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm ci


build: off

test_script:
  - cmd: npm run lint
  - cmd: npm test

cache:
  - node_modules -> package.json

deploy_script:
  - ps: |
      if ($ENV:APPVEYOR_REPO_TAG_NAME)
      {
        "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII
        iex "npm publish --access public"
      }
    on:
      branch: master
      appveyor_repo_tag: true
